# Generated by Django 4.2.2 on 2023-06-26 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_repoinsightproject"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User_RepoInsightProject",
            new_name="UserRepoinsihtProject",
        ),
    ]
