# Generated by Django 4.2.2 on 2023-06-27 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_repoinsightproject_userrepoinsihtproject"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserRepoinsihtProject",
            new_name="UserRepoInsightProject",
        ),
    ]
