# Generated by Django 4.2.1 on 2023-06-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoinsights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
