# Generated by Django 4.2.2 on 2023-06-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repoinsights", "0004_extractions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField()),
                ("message", models.CharField(max_length=256)),
                ("ext_ref_id", models.CharField(max_length=32)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_commits",
                        to="repoinsights.user",
                    ),
                ),
                (
                    "committer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committed_commits",
                        to="repoinsights.user",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="repoinsights.project",
                    ),
                ),
            ],
        ),
    ]
