# Generated by Django 4.2.2 on 2023-06-27 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repoinsights", "0005_commit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commit",
            options={"managed": False},
        ),
    ]
