# Generated by Django 4.2.2 on 2023-06-27 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("repoinsights", "0006_alter_commit_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="commit",
            table="commits",
        ),
    ]
