# Generated by Django 4.2.3 on 2023-07-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("repoinsights", "0007_alter_commit_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("measurement_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "metrics",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectMetrics",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repoinsights.extractions",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repoinsights.metrics",
                    ),
                ),
            ],
            options={
                "db_table": "project_metrics",
            },
        ),
    ]
