# Generated by Django 4.2.1 on 2023-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_userprivaterepos_privaterepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
