# Generated by Django 4.2.1 on 2023-05-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
