# Generated by Django 4.2.3 on 2023-07-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0010_alter_usertokens_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="privaterepository",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
