# Generated by Django 4.2.1 on 2023-05-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metabaseuserdata',
            old_name='metabse_id',
            new_name='metabase_id',
        ),
        migrations.RemoveField(
            model_name='metabaseuserdata',
            name='email',
        ),
    ]
